services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # DataFixtures services - only available in dev environment
    Tourze\StockCostBundle\DataFixtures\:
        resource: '../../DataFixtures/'
        tags: [doctrine.fixture.orm]